version: "3.4"
services:
  web:
    image: "nginx:${DOCKER_NGINX_VERSION}"
    ports:
      - "${DOCKER_NGINX_WEB_PORT}:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - .:/app
    depends_on:
      - php
  php:
    build:
      context: ./
      dockerfile: "php-dockerfile"
      args:
        - DOCKER_PHP_VERSION
        - DOCKER_PHP_XDEBUG_ENABLED
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      XDEBUG_CONFIG: client_host=${DOCKER_PHP_XDEBUG_REMOTE_HOST} client_port=${DOCKER_PHP_XDEBUG_REMOTE_PORT}
      PHP_IDE_CONFIG: serverName=${DOCKER_PHP_XDEBUG_IDE_KEY}
    depends_on:
      - db
  db:
    image: "mysql:${DOCKER_MYSQL_VERSION}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
