services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\Weather\ResponseToReadingTransformer:
        class: 'App\Service\Weather\ResponseToReadingTransformer'
        public: true
